### ISSUE TITLE
Research Topic

### ISSUE THREAD

**Issue by cbrown4776** [slu-soc5650/lecture-01#1]
State what your research question 
How does the number food desserts effect the crime rate in St Louis Metropolitan area?

Identify the data you are using to address that question
I will be using crime data as well as grocery store locations to generate spacial data to assist the two issues. 

The main category within the data you would like to map
Crime and Grocery store locations.

**Comment by chris-prener** [comment]
hey @cbrown4776 - I'm going to close this and follow-up with you in your `BrownProject` repository!
